// List taken from https://vsx.aavso.org/index.php?view=about.vartypes

const normalizedVarTypeDescriptions: Record<string, string> = {
  EA: "Eclipsing binary, Algol type",
  SRB: "Semiregular",
  "?": "Unknown, needs more observations",
  GCAS: "Gamma Cassiopeae type",
  LB: "Long irregular",
  EB: "Eclipsing binary, Beta Lyrae type",
  RS: "RS Canum Venaticorum type",
  SR: "Semiregular",
  DCEP: "Classical Cepheid",
  SRS: "Semiregular",
  EW: "Eclipsing binary, W Ursae Maioris",
  LC: "Long irregular",
  SRC: "Semiregular",
  BE: "Be star",
  DSCT: "Delta Scuti",
  ACV: "Alpha2 Canum Venaticorum",
  SRD: "Semiregular",
  ELL: "Rotating ellipsoidal",
  BY: "BY Draconis",
  ACYG: "Alpha Cygni",
  SRA: "Semiregular",
  E: "Eclipsing binary, unknown type",
  L: "Long irregular",
  GDOR: "Gamma Doradus",
  DPV: "Double Periodic Variables",
  ZAND: "Z Andromedae",
  WTTS: "Weak T Tauri",
  MISC: "Unknown, needs more observations",
  INA: "Orion variable",
  ROT: "Rotating, unknown type",
  BCEP: "Beta Cephei",
  UXOR: "UX Orionis",
  TTS: "T Tauri",
  SXARI: "SX Arietis",
  M: "Mira variable",
  YHG: "Yellow hypergiant",
  RVA: "RV Tauri",
  RRAB: "RR Lyrae, asymmetric curve",
  IB: "Irregular, needs more observation",
  HMXB: "High mass X-ray binary",
  YSO: "T Tauri like",
  WR: "Wolf-Rayet",
  UV: "UV Ceti (flare)",
  SDOR: "Luminous blue variable",
  PVTELIII: "PV Telescopii",
  I: "Irregular, needs more observations",
  CWB: "Type II Cepheid",
  SXPHE: "Delta Scuti-like",
  SPB: "53 Persei",
  S: "Semiregular",
  RVB: "RV Tauri",
  RRC: "RR Lyrae, symmetric curve",
  PVTELI: "PV Telescopii",
  PPN: "Yellow supergiant",
  LERI: "Be star",
  INSA: "Rapid irregular",
  FSCMa: "Be type",
  CWA: "Type II Cepheid",
  CST: "Previously suspected variable",
  SPBe: "Be star",
  RV: "RV Tauri",
  RRD: "RR Lyrae, double mode",
  R: "Close binary",
  LPV: "Long period variable, unknown type",
  ISB: "Irregular",
  IA: "Irregular, needs more observations",
  FKCOM: "FK Comae Berenices",
  ESD: "synonym for EA and EB",
  EC: "synonym for EW",
  DSCTR: "Delta Scuti",
  CTTS: "T Tauri",
  ACEP: "Anomalous Cepheid",
  DSCTr: "Delta Scuti contact binary",
};

export default normalizedVarTypeDescriptions;
